config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'about', to: 'about#index'

  resources :users do 
    resources :bookmarks
  end 
  
  resources :reviews do
    resources :comments
  end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :review
  belongs_to :user
  
end

app/models/review.rb
class Review < ApplicationRecord

  validates :title, presence: true
  validates :title, length: { maximum: 210 }
  validates :body, presence: true
  validates :link, presence: true

  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :users

  def self.search_results(search_term)
    wildcard = "%#{search_term}%"
    where('title LIKE ?', wildcard).or(where('body LIKE ?', wildcard).or(where('author LIKE ?', wildcard)))
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :reviews
  has_many :comments 
  has_and_belongs_to_many :bookmarks, class_name: 'Review'
  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @has_user_signed = session[:user_id].present?
    if @has_user_signed
      @user = session[:user_id]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create 
    @review = Review.find(params[:review_id])
    @user = User.find(params[:user_id])
    @user.bookmarks << @review
    redirect_back(fallback_location: review_path(@review))
  end 

  def destroy 
    @review = Review.find(params[:review_id])
    @user = User.find(params[:user_id])
    @user.bookmarks.destroy @review
    redirect_back(fallback_location: review_path(@review))
  end 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create 
    @comment = Comment.new(comment_params)
    @comment.user = User.find(session[:user_id])
    @comment.review = Review.find(params[:review_id])
    @comment.save
    redirect_to(review_path(params[:review_id]))
  end 

  private 

  def comment_params 
    params.require(:comment).permit(:body)
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @has_user_signed = session[:user_id].present?
    if @has_user_signed
      @user = session[:user_id]
    end
  end 

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @has_user_signed = session[:user_id].present?
    if @has_user_signed
      @user = session[:user_id]
    end
    @search_term = params[:q]
    @reviews = Review.all
    if @search_term
      @reviews = Review.search_results(@search_term)
    end
  end

  def new 
    @has_user_signed = session[:user_id].present?
    if @has_user_signed
      @user = session[:user_id]
    end
    @review = Review.new
  end 

  def create 
    @review = Review.new(review_params)
    @review.user = User.find(session[:user_id])
    if (@review.save)
      redirect_to(review_path(@review))
    else
      render 'new'
    end 
  end 

  def edit 
    @has_user_signed = session[:user_id].present?
    if @has_user_signed
      @user = session[:user_id]
    end
    @review = Review.find(params[:id])
  end 

  def update
    @review = Review.find(params[:id])
    if (@review.update(review_params))
      redirect_to(review_path(@review))
    else
      render 'edit'
    end 
  end 

  def show 
    @has_user_signed = session[:user_id].present?
    if @has_user_signed
      @user = User.find(session[:user_id])
      @comment = Comment.new
      @is_bookmarked = @user.bookmarks.exists?(params[:id])
    end
    @review = Review.find(params[:id])
  end 

  private 

  def review_params 
    params.require(:review).permit(:title, :author, :image_url, :link, :body)
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @has_user_signed = session[:user_id].present?
    if @has_user_signed
      @user = session[:user_id]
    end
    @user = User.new
  end 

  def create 
    user = User.find_or_create_by(user_params)
    session[:user_id] = user.id
    redirect_to(user_path(user))
  end 

  def show 
    @has_user_signed = session[:user_id].present?
    if @has_user_signed
      @user = User.find(session[:user_id])
    end
  end 

  private 

  def user_params 
    params.require(:user).permit(:username, :email)
  end 

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/application/_card_btn_bookmark.html.erb
<% if(@is_bookmarked) %>
  <%= form_tag(user_bookmark_path(@user, @review), method: :delete) do %>
    <%= hidden_field_tag('review_id', @review.id) %>
    <%= button_tag('Un-Bookmark', type: 'submit') %>
  <% end %>
<% else %>
  <%= form_tag(user_bookmarks_path(@user)) do %>
    <%= hidden_field_tag('review_id', @review.id) %>
    <%= button_tag('Bookmark', type: 'submit') %>
  <% end %>
<% end %>

app/views/application/_card_btn_editable.html.erb
<%= link_to('Edit', edit_review_path(review)) %>

app/views/application/_card_review.html.erb
<%= image_tag(review.image_url) %>
<h3><%= review.title %></h3>
<span><%= review.author %></span>
<div>
  <%= link_to('Details', review_path(review)) %>
</div>

app/views/application/_footer.html.erb
<footer>
Footer
</footer>

app/views/application/_header.html.erb
<header class='container-fluid navbar pb-3 mb-5 border border-warning border-top-0 border-right-0 border-left-0 justify-content-center justify-content-sm-around'>
  <div>
    <%= link_to(root_path, class: 'navbar-brand') do %>
      <%= image_tag('logo_cool_cast.png', alt: 'Logo CoolCast') %>
    <% end %>
  </div>
  <div>
    <%= form_tag(reviews_path, class: 'form-inline flex-nowrap', method: 'GET') do %>
      <label class='sr-only' for='q'>Looking for a podcast</label>
      <%= text_field_tag('q', nil, placeholder: 'Search', class: 'form-control') %>
      <%= submit_tag('Search', class: 'btn btn-warning my-2 my-sm-0', name: nil) %>
    <% end %>
  </div>
  <nav>
    <ul class='nav mr-sm-5 pt-4 pt-sm-0'>
      <li class='nav-item ml-3 ml-sm-5'><%= link_to('ABOUT', about_path) %></li>
      <li class='nav-item ml-3 ml-sm-5'><%= link_to('PODCASTS', reviews_path) %></li>
      <%# User menu %>
      <% if(@has_user_signed) %>
        <li class='nav-item ml-3 ml-sm-5'><%= link_to('ACCOUNT', user_path(@user)) %></li>
      <%# Visitor menu %>
      <% else %>
        <li class='nav-item ml-3 ml-sm-5'><%= link_to('LOG IN / REGISTER', new_user_path) %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/home/index.html.erb
<h1>Root of the Cool Cast App</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoolCast</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render(partial: 'header') %>
    <%= yield %>
    <%= render(partial: 'footer') %>
  </body>
</html>

app/views/reviews/_form_review.html.erb
<% if(review.errors.any?) %>
  <% for error in review.errors.full_messages do %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= form_for(review) do |form| %>
  <%= form.label(:title, 'Podcast title') %>
  <%= form.text_field(:title, placeholder: 'The Joe Rogan Experience') %>
  <%= form.label(:author, 'Podcast Author') %>
  <%= form.text_field(:author, placeholder: 'Joe Rogan') %>
  <%= form.label(:image_url, 'Podcast image') %>
  <%= form.text_field(:image_url) %>
  <%= form.label(:link, 'Podcast link') %>
  <%= form.text_field(:link, placeholder: 'http://podcasts.joerogan.net/') %>
  <%= form.label(:body, 'Your review') %>
  <%= form.text_area(:body) %>
  <%= form.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Reviews Edit</h1>
<%= render(partial: 'form_review', locals: {review: @review}) %>

app/views/reviews/index.html.erb
<% if(@search_term) %>
  <h1>Results for "<%= @search_term %>"</h1>
  <% if(@reviews.length < 1) %>
    <p>No result to display</p>
  <% else %>
    <ul>
      <% for review in @reviews do %>
        <li><%= render(partial: 'card_review', locals: {review: review}) %> </li>
      <% end %>
    </ul>
  <% end %>
<% else %>
  <h1>All the Reviews</h1>
  <ul>
    <% for review in @reviews do %>
      <li><%= render(partial: 'card_review', locals: {review: review}) %> </li>
    <% end %>
  </ul>
<% end %>

app/views/reviews/new.html.erb
<h1>Reviews Create</h1>
<%= render(partial: 'form_review', locals: {review: @review}) %>

app/views/reviews/show.html.erb
<h1>Reviews Show</h1>
<ul>
  <li><%= @review.title %></li>
  <li><%= @review.author %></li>
  <li><%= @review.link %></li>
  <li><%= @review.image_url %></li>
  <li><%= @review.body %></li>
</ul>

<% if(@has_user_signed) %>
  <% if(@is_bookmarked) %>
    <%= form_tag(user_bookmark_path(@user, @review), method: :delete) do %>
      <%= hidden_field_tag('review_id', @review.id) %>
      <%= button_tag('Un-Bookmark', type: 'submit') %>
    <% end %>
  <% else %>
    <%= form_tag(user_bookmarks_path(@user)) do %>
      <%= hidden_field_tag('review_id', @review.id) %>
      <%= button_tag('Bookmark', type: 'submit') %>
    <% end %>
  <% end %>
<% end %>

<% if(@has_user_signed) %>
  <%= form_for([@review, @comment]) do |form| %>
    <%= form.label(:body, 'Add a comment') %>
    <%= form.text_area(:body) %>
    <%= form.submit %>
  <% end %>
<% end %>
<% if(@review.comments.any?) %>
  <ul>
    <% @review.comments.each do |comment| %>
      <li><%= comment.body %></li>    
    <% end %>
  </ul>
<% else %>
  <p>No comment to display</p>
<% end %>

app/views/users/new.html.erb
<h1>Log in / Register</h1>

<%= form_for(@user) do |form| %>
  <%= form.label(:username, 'Username') %>
  <%= form.text_field(:username, placeholder: 'Your Username') %>
  <%= form.label(:email, 'Email') %>
  <%= form.text_field(:email, placeholder: 'user@user.ch') %>
  <%= form.submit('Log in') %>
<% end %>

app/views/users/show.html.erb
<h1>My account</h1>
<%= @message %>